//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactanos
    {
        public string Correo { get; set; }
        public string Queja { get; set; }
        public string Felicitación { get; set; }
        public string Consulta_de_inscripción { get; set; }
        public string Otra { get; set; }
        public int ID_Consultorio { get; set; }
    }
}
