//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingenierías
    {
        public string nombre_de_carrera { get; set; }
        public string titulo_por_otorgar { get; set; }
        public string objetivos { get; set; }
        public string ofertada { get; set; }
        public int ID_Carrera { get; set; }
    }
}
